#!/bin/sh
[ "$1" != "upgrade" ] || exit 0 > /dev/null 2>&1
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/ChocholousekPicons > /dev/null 2>&1
echo "*********************************************************"
echo "      PiconHub-Warder-Evolution - ver.5.0.240904.2        "
echo "                Enigma2 plugin/extensions                "
echo " https://github.com/Evolution-by-Warder/PiconHub-Warder-Evolution "
echo "*********************************************************"
echo "  Successfully REMOVED. You should restart Enigma2 now.  "
echo "*********************************************************"
exit 0
